version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: manager
      POSTGRES_PASSWORD: example
      POSTGRES_DB: manager_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  manager-api:
    build: ./manager/
    depends_on:
      - db
    ports:
      - 8090:8090
    environment:
      PORT: 8090
      CONNECTION_STRING: postgres://manager:example@db/manager_db